name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: esp32_latest
        esp_idf_docker_image: espressif/idf-rust
        command: |
          cargo doc --verbose
          cargo fmt --verbose
          cargo build --verbose
