name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: esp32_latest
        esp_idf_docker_image: espressif/idf-rust
    - name: RustDoc
      run: cargo doc --verbose
    - name: Build
      run: cargo fmt --verbose
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
