name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: espressif/idf-rust:esp32_latest
      options: --user root

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: RustDoc
      run: cargo doc --verbose
    - name: fmt
      run: cargo fmt --verbose
    - name: Build
      run: cargo build --verbose
